// <auto-generated />
using System;
using KSheet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KSheet.Migrations
{
    [DbContext(typeof(CallContext))]
    partial class CallContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("KSheet.Data.Call", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FdSignal")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Incident")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PdSignal")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Position")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Calls", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "16 Barby Park",
                            FdSignal = "44",
                            Incident = 306876,
                            Notes = "Polarised needs-based policy",
                            PdSignal = "51",
                            Position = 141,
                            Time = new DateTime(2012, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Address = "0790 Elmside Crossing",
                            FdSignal = "44",
                            Incident = 733328,
                            Notes = "Up-sized web-enabled instruction set",
                            PdSignal = "41",
                            Position = 114,
                            Time = new DateTime(2017, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Address = "220 Prentice Avenue",
                            FdSignal = "42",
                            Incident = 365002,
                            Notes = "Persistent directional attitude",
                            PdSignal = "54",
                            Position = 115,
                            Time = new DateTime(2001, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Address = "85465 Buell Hill",
                            FdSignal = "42",
                            Incident = 704130,
                            Notes = "Focused fresh-thinking moratorium",
                            PdSignal = "36",
                            Position = 132,
                            Time = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Address = "1 Ronald Regan Alley",
                            FdSignal = "37",
                            Incident = 988168,
                            Notes = "Reverse-engineered solution-oriented installation",
                            PdSignal = "14",
                            Position = 146,
                            Time = new DateTime(2008, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Address = "09744 Tomscot Terrace",
                            FdSignal = "44",
                            Incident = 819494,
                            Notes = "Horizontal scalable attitude",
                            PdSignal = "10",
                            Position = 130,
                            Time = new DateTime(2006, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Address = "41988 Sutherland Road",
                            FdSignal = "35",
                            Incident = 545423,
                            Notes = "Advanced context-sensitive info-mediaries",
                            PdSignal = "49",
                            Position = 109,
                            Time = new DateTime(2001, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Address = "1598 Superior Parkway",
                            FdSignal = "44",
                            Incident = 975076,
                            Notes = "Operative mission-critical project",
                            PdSignal = "53",
                            Position = 130,
                            Time = new DateTime(2019, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Address = "8553 Bashford Trail",
                            FdSignal = "41",
                            Incident = 243339,
                            Notes = "Sharable bottom-line contingency",
                            PdSignal = "24",
                            Position = 124,
                            Time = new DateTime(1997, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Address = "6 Burrows Crossing",
                            FdSignal = "15",
                            Incident = 849034,
                            Notes = "Reverse-engineered 24 hour hub",
                            PdSignal = "41",
                            Position = 133,
                            Time = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Address = "9895 Del Mar Court",
                            FdSignal = "40",
                            Incident = 287667,
                            Notes = "Organized grid-enabled matrices",
                            PdSignal = "16",
                            Position = 143,
                            Time = new DateTime(2001, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Address = "14 Comanche Place",
                            FdSignal = "20",
                            Incident = 806781,
                            Notes = "Multi-layered leading edge local area network",
                            PdSignal = "11",
                            Position = 158,
                            Time = new DateTime(2002, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Address = "4577 Talisman Place",
                            FdSignal = "34",
                            Incident = 707657,
                            Notes = "Down-sized coherent groupware",
                            PdSignal = "31",
                            Position = 131,
                            Time = new DateTime(2021, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Address = "11 Rieder Point",
                            FdSignal = "28",
                            Incident = 620511,
                            Notes = "Mandatory value-added focus group",
                            PdSignal = "17",
                            Position = 149,
                            Time = new DateTime(2020, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Address = "57496 Maywood Terrace",
                            FdSignal = "29",
                            Incident = 620408,
                            Notes = "Operative intermediate encryption",
                            PdSignal = "50",
                            Position = 146,
                            Time = new DateTime(2000, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Address = "14466 Rockefeller Hill",
                            FdSignal = "27",
                            Incident = 571289,
                            Notes = "Cloned reciprocal circuit",
                            PdSignal = "27",
                            Position = 141,
                            Time = new DateTime(2013, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Address = "0 Dayton Crossing",
                            FdSignal = "45",
                            Incident = 476600,
                            Notes = "Business-focused full-range firmware",
                            PdSignal = "18",
                            Position = 104,
                            Time = new DateTime(2004, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Address = "408 Shelley Court",
                            FdSignal = "19",
                            Incident = 219875,
                            Notes = "Implemented well-modulated alliance",
                            PdSignal = "46",
                            Position = 150,
                            Time = new DateTime(2014, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            Address = "6216 Dorton Center",
                            FdSignal = "34",
                            Incident = 767288,
                            Notes = "Inverse contextually-based process improvement",
                            PdSignal = "51",
                            Position = 160,
                            Time = new DateTime(2021, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            Address = "82 Dovetail Road",
                            FdSignal = "30",
                            Incident = 743809,
                            Notes = "De-engineered value-added software",
                            PdSignal = "17",
                            Position = 120,
                            Time = new DateTime(1996, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            Address = "5960 Scofield Place",
                            FdSignal = "47",
                            Incident = 303199,
                            Notes = "Optimized heuristic moderator",
                            PdSignal = "26",
                            Position = 129,
                            Time = new DateTime(2015, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            Address = "76548 Summit Parkway",
                            FdSignal = "32",
                            Incident = 429386,
                            Notes = "Assimilated empowering process improvement",
                            PdSignal = "17",
                            Position = 151,
                            Time = new DateTime(2000, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            Address = "65 Iowa Way",
                            FdSignal = "35",
                            Incident = 125483,
                            Notes = "Profit-focused full-range open system",
                            PdSignal = "18",
                            Position = 154,
                            Time = new DateTime(2016, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            Address = "1 Golf Road",
                            FdSignal = "25",
                            Incident = 916552,
                            Notes = "Versatile optimal protocol",
                            PdSignal = "22",
                            Position = 137,
                            Time = new DateTime(1998, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            Address = "79 Bluestem Hill",
                            FdSignal = "32",
                            Incident = 895954,
                            Notes = "Versatile homogeneous emulation",
                            PdSignal = "19",
                            Position = 147,
                            Time = new DateTime(2005, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            Address = "29 Crowley Center",
                            FdSignal = "49",
                            Incident = 868575,
                            Notes = "Organic 4th generation service-desk",
                            PdSignal = "28",
                            Position = 126,
                            Time = new DateTime(2001, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            Address = "324 Gateway Terrace",
                            FdSignal = "44",
                            Incident = 246925,
                            Notes = "Advanced national implementation",
                            PdSignal = "10",
                            Position = 122,
                            Time = new DateTime(2014, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            Address = "316 Knutson Junction",
                            FdSignal = "43",
                            Incident = 759686,
                            Notes = "Automated intangible encryption",
                            PdSignal = "47",
                            Position = 111,
                            Time = new DateTime(2016, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            Address = "2558 Sauthoff Parkway",
                            FdSignal = "26",
                            Incident = 204818,
                            Notes = "Enterprise-wide content-based pricing structure",
                            PdSignal = "51",
                            Position = 142,
                            Time = new DateTime(2003, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            Address = "276 Crowley Road",
                            FdSignal = "20",
                            Incident = 602076,
                            Notes = "Right-sized needs-based application",
                            PdSignal = "17",
                            Position = 124,
                            Time = new DateTime(2002, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            Address = "135 Helena Crossing",
                            FdSignal = "33",
                            Incident = 963527,
                            Notes = "Vision-oriented stable challenge",
                            PdSignal = "30",
                            Position = 113,
                            Time = new DateTime(1997, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            Address = "542 Dahle Terrace",
                            FdSignal = "23",
                            Incident = 293820,
                            Notes = "Grass-roots bi-directional task-force",
                            PdSignal = "50",
                            Position = 150,
                            Time = new DateTime(2010, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            Address = "86 Hagan Road",
                            FdSignal = "37",
                            Incident = 884891,
                            Notes = "Self-enabling intermediate data-warehouse",
                            PdSignal = "47",
                            Position = 143,
                            Time = new DateTime(2013, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            Address = "2022 Sutteridge Court",
                            FdSignal = "36",
                            Incident = 560421,
                            Notes = "Polarised multi-tasking pricing structure",
                            PdSignal = "37",
                            Position = 137,
                            Time = new DateTime(1995, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            Address = "9408 Butternut Parkway",
                            FdSignal = "41",
                            Incident = 235074,
                            Notes = "Upgradable value-added analyzer",
                            PdSignal = "38",
                            Position = 142,
                            Time = new DateTime(2020, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            Address = "8680 Cascade Junction",
                            FdSignal = "30",
                            Incident = 638378,
                            Notes = "Proactive client-server adapter",
                            PdSignal = "16",
                            Position = 128,
                            Time = new DateTime(2017, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            Address = "04806 Monument Place",
                            FdSignal = "44",
                            Incident = 515460,
                            Notes = "Reduced 24 hour software",
                            PdSignal = "35",
                            Position = 124,
                            Time = new DateTime(2012, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            Address = "418 Pine View Street",
                            FdSignal = "39",
                            Incident = 857433,
                            Notes = "Profit-focused secondary frame",
                            PdSignal = "44",
                            Position = 155,
                            Time = new DateTime(2013, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            Address = "14074 Blackbird Pass",
                            FdSignal = "18",
                            Incident = 594107,
                            Notes = "Object-based upward-trending paradigm",
                            PdSignal = "36",
                            Position = 160,
                            Time = new DateTime(2004, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            Address = "33 Mockingbird Way",
                            FdSignal = "18",
                            Incident = 189863,
                            Notes = "User-centric mission-critical capability",
                            PdSignal = "54",
                            Position = 101,
                            Time = new DateTime(2014, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 41,
                            Address = "88779 Helena Place",
                            FdSignal = "17",
                            Incident = 287843,
                            Notes = "Open-source maximized initiative",
                            PdSignal = "37",
                            Position = 130,
                            Time = new DateTime(1998, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 42,
                            Address = "23592 Monterey Center",
                            FdSignal = "15",
                            Incident = 340306,
                            Notes = "Cloned national orchestration",
                            PdSignal = "30",
                            Position = 143,
                            Time = new DateTime(2017, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 43,
                            Address = "24 Emmet Street",
                            FdSignal = "49",
                            Incident = 873478,
                            Notes = "Function-based empowering portal",
                            PdSignal = "31",
                            Position = 141,
                            Time = new DateTime(2011, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 44,
                            Address = "64636 East Point",
                            FdSignal = "32",
                            Incident = 182172,
                            Notes = "Switchable uniform emulation",
                            PdSignal = "37",
                            Position = 141,
                            Time = new DateTime(2002, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 45,
                            Address = "48 Nevada Terrace",
                            FdSignal = "16",
                            Incident = 546911,
                            Notes = "Up-sized web-enabled parallelism",
                            PdSignal = "45",
                            Position = 102,
                            Time = new DateTime(1996, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 46,
                            Address = "364 Laurel Point",
                            FdSignal = "27",
                            Incident = 388000,
                            Notes = "Total needs-based portal",
                            PdSignal = "50",
                            Position = 136,
                            Time = new DateTime(2004, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 47,
                            Address = "79741 Dahle Pass",
                            FdSignal = "33",
                            Incident = 839263,
                            Notes = "Function-based discrete throughput",
                            PdSignal = "55",
                            Position = 160,
                            Time = new DateTime(2004, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 48,
                            Address = "541 Northridge Point",
                            FdSignal = "22",
                            Incident = 777107,
                            Notes = "Pre-emptive next generation open system",
                            PdSignal = "21",
                            Position = 155,
                            Time = new DateTime(2009, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 49,
                            Address = "7 Tony Junction",
                            FdSignal = "22",
                            Incident = 915877,
                            Notes = "Triple-buffered stable groupware",
                            PdSignal = "43",
                            Position = 116,
                            Time = new DateTime(1998, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 50,
                            Address = "927 Manufacturers Lane",
                            FdSignal = "24",
                            Incident = 362449,
                            Notes = "Focused optimal time-frame",
                            PdSignal = "40",
                            Position = 150,
                            Time = new DateTime(2018, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 51,
                            Address = "56244 Charing Cross Drive",
                            FdSignal = "19",
                            Incident = 344237,
                            Notes = "Triple-buffered 6th generation flexibility",
                            PdSignal = "25",
                            Position = 133,
                            Time = new DateTime(2004, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 52,
                            Address = "3514 Southridge Point",
                            FdSignal = "24",
                            Incident = 505289,
                            Notes = "Profit-focused leading edge productivity",
                            PdSignal = "53",
                            Position = 157,
                            Time = new DateTime(2014, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 53,
                            Address = "771 Mallory Street",
                            FdSignal = "26",
                            Incident = 906690,
                            Notes = "Devolved value-added success",
                            PdSignal = "21",
                            Position = 152,
                            Time = new DateTime(2008, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 54,
                            Address = "13307 Magdeline Terrace",
                            FdSignal = "39",
                            Incident = 258410,
                            Notes = "Extended value-added migration",
                            PdSignal = "27",
                            Position = 158,
                            Time = new DateTime(2000, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 55,
                            Address = "7 Claremont Circle",
                            FdSignal = "19",
                            Incident = 862893,
                            Notes = "Open-source local knowledge user",
                            PdSignal = "14",
                            Position = 150,
                            Time = new DateTime(2002, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 56,
                            Address = "63 Donald Plaza",
                            FdSignal = "23",
                            Incident = 984681,
                            Notes = "User-centric client-server core",
                            PdSignal = "36",
                            Position = 116,
                            Time = new DateTime(2018, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 57,
                            Address = "7132 Upham Center",
                            FdSignal = "29",
                            Incident = 984292,
                            Notes = "Intuitive heuristic extranet",
                            PdSignal = "27",
                            Position = 138,
                            Time = new DateTime(2019, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 58,
                            Address = "38623 Petterle Terrace",
                            FdSignal = "34",
                            Incident = 287572,
                            Notes = "Pre-emptive hybrid budgetary management",
                            PdSignal = "41",
                            Position = 132,
                            Time = new DateTime(2021, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 59,
                            Address = "37197 Pleasure Way",
                            FdSignal = "49",
                            Incident = 561248,
                            Notes = "Diverse dynamic migration",
                            PdSignal = "41",
                            Position = 152,
                            Time = new DateTime(2020, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 60,
                            Address = "21 Anderson Center",
                            FdSignal = "24",
                            Incident = 625114,
                            Notes = "Face to face regional secured line",
                            PdSignal = "41",
                            Position = 156,
                            Time = new DateTime(1997, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 61,
                            Address = "77 Garrison Hill",
                            FdSignal = "37",
                            Incident = 749999,
                            Notes = "Customer-focused reciprocal productivity",
                            PdSignal = "44",
                            Position = 104,
                            Time = new DateTime(2007, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 62,
                            Address = "98874 Warbler Court",
                            FdSignal = "49",
                            Incident = 773200,
                            Notes = "Quality-focused motivating attitude",
                            PdSignal = "51",
                            Position = 137,
                            Time = new DateTime(2001, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 63,
                            Address = "5 Merchant Place",
                            FdSignal = "49",
                            Incident = 160597,
                            Notes = "Reduced 24 hour website",
                            PdSignal = "55",
                            Position = 130,
                            Time = new DateTime(2013, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 64,
                            Address = "7 Forest Run Alley",
                            FdSignal = "22",
                            Incident = 705657,
                            Notes = "Programmable exuding budgetary management",
                            PdSignal = "27",
                            Position = 144,
                            Time = new DateTime(1999, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 65,
                            Address = "793 Sage Junction",
                            FdSignal = "21",
                            Incident = 481306,
                            Notes = "Fundamental foreground product",
                            PdSignal = "19",
                            Position = 123,
                            Time = new DateTime(1995, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 66,
                            Address = "0782 Fremont Park",
                            FdSignal = "48",
                            Incident = 789659,
                            Notes = "User-centric executive superstructure",
                            PdSignal = "18",
                            Position = 150,
                            Time = new DateTime(2008, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 67,
                            Address = "501 Walton Lane",
                            FdSignal = "15",
                            Incident = 449683,
                            Notes = "Extended homogeneous toolset",
                            PdSignal = "27",
                            Position = 119,
                            Time = new DateTime(2018, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 68,
                            Address = "104 Debra Lane",
                            FdSignal = "36",
                            Incident = 108753,
                            Notes = "Mandatory coherent intranet",
                            PdSignal = "47",
                            Position = 107,
                            Time = new DateTime(2023, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 69,
                            Address = "71881 Valley Edge Court",
                            FdSignal = "47",
                            Incident = 213963,
                            Notes = "Versatile maximized strategy",
                            PdSignal = "46",
                            Position = 124,
                            Time = new DateTime(2005, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 70,
                            Address = "8 Maple Center",
                            FdSignal = "45",
                            Incident = 906827,
                            Notes = "Front-line grid-enabled interface",
                            PdSignal = "54",
                            Position = 117,
                            Time = new DateTime(2022, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 71,
                            Address = "737 Basil Center",
                            FdSignal = "44",
                            Incident = 285726,
                            Notes = "Extended dynamic software",
                            PdSignal = "17",
                            Position = 138,
                            Time = new DateTime(2001, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 72,
                            Address = "15 Arkansas Hill",
                            FdSignal = "40",
                            Incident = 444584,
                            Notes = "Versatile intangible extranet",
                            PdSignal = "24",
                            Position = 137,
                            Time = new DateTime(2023, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 73,
                            Address = "65416 Bellgrove Hill",
                            FdSignal = "43",
                            Incident = 227531,
                            Notes = "Versatile bifurcated matrices",
                            PdSignal = "19",
                            Position = 142,
                            Time = new DateTime(2023, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 74,
                            Address = "943 Bunting Street",
                            FdSignal = "23",
                            Incident = 312959,
                            Notes = "Face to face zero tolerance customer loyalty",
                            PdSignal = "24",
                            Position = 143,
                            Time = new DateTime(1996, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 75,
                            Address = "6 Merchant Avenue",
                            FdSignal = "42",
                            Incident = 970189,
                            Notes = "Pre-emptive discrete data-warehouse",
                            PdSignal = "25",
                            Position = 128,
                            Time = new DateTime(2020, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 76,
                            Address = "92658 Commercial Terrace",
                            FdSignal = "29",
                            Incident = 135922,
                            Notes = "Realigned bottom-line projection",
                            PdSignal = "42",
                            Position = 160,
                            Time = new DateTime(2016, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 77,
                            Address = "17605 Wayridge Road",
                            FdSignal = "19",
                            Incident = 686952,
                            Notes = "Enhanced optimizing functionalities",
                            PdSignal = "22",
                            Position = 145,
                            Time = new DateTime(2014, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 78,
                            Address = "5918 Messerschmidt Trail",
                            FdSignal = "23",
                            Incident = 363085,
                            Notes = "Managed dynamic projection",
                            PdSignal = "30",
                            Position = 150,
                            Time = new DateTime(2015, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 79,
                            Address = "0196 Packers Avenue",
                            FdSignal = "31",
                            Incident = 197103,
                            Notes = "Virtual bifurcated throughput",
                            PdSignal = "43",
                            Position = 118,
                            Time = new DateTime(2007, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 80,
                            Address = "66 Bay Trail",
                            FdSignal = "33",
                            Incident = 608439,
                            Notes = "Synergized fresh-thinking alliance",
                            PdSignal = "23",
                            Position = 148,
                            Time = new DateTime(2004, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 81,
                            Address = "082 Little Fleur Hill",
                            FdSignal = "38",
                            Incident = 912076,
                            Notes = "Multi-layered empowering secured line",
                            PdSignal = "18",
                            Position = 149,
                            Time = new DateTime(2017, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 82,
                            Address = "433 Nova Way",
                            FdSignal = "25",
                            Incident = 431833,
                            Notes = "Stand-alone transitional installation",
                            PdSignal = "53",
                            Position = 121,
                            Time = new DateTime(2019, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 83,
                            Address = "08414 Vernon Trail",
                            FdSignal = "49",
                            Incident = 848406,
                            Notes = "Robust methodical moratorium",
                            PdSignal = "48",
                            Position = 116,
                            Time = new DateTime(2023, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 84,
                            Address = "3327 Mayfield Pass",
                            FdSignal = "18",
                            Incident = 170695,
                            Notes = "Profit-focused 24 hour toolset",
                            PdSignal = "16",
                            Position = 156,
                            Time = new DateTime(2017, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 85,
                            Address = "32717 Melby Terrace",
                            FdSignal = "44",
                            Incident = 680604,
                            Notes = "Managed dedicated implementation",
                            PdSignal = "31",
                            Position = 136,
                            Time = new DateTime(2008, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 86,
                            Address = "0374 Ruskin Plaza",
                            FdSignal = "22",
                            Incident = 523648,
                            Notes = "Decentralized client-server interface",
                            PdSignal = "12",
                            Position = 140,
                            Time = new DateTime(1997, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 87,
                            Address = "84450 Evergreen Way",
                            FdSignal = "42",
                            Incident = 355088,
                            Notes = "Quality-focused disintermediate structure",
                            PdSignal = "46",
                            Position = 137,
                            Time = new DateTime(2021, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 88,
                            Address = "5765 American Point",
                            FdSignal = "15",
                            Incident = 871204,
                            Notes = "Decentralized bandwidth-monitored circuit",
                            PdSignal = "16",
                            Position = 156,
                            Time = new DateTime(2020, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 89,
                            Address = "9563 Ruskin Court",
                            FdSignal = "46",
                            Incident = 471207,
                            Notes = "Organic asynchronous customer loyalty",
                            PdSignal = "45",
                            Position = 105,
                            Time = new DateTime(2000, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 90,
                            Address = "6 Mallory Hill",
                            FdSignal = "42",
                            Incident = 614140,
                            Notes = "Integrated context-sensitive utilisation",
                            PdSignal = "22",
                            Position = 145,
                            Time = new DateTime(2008, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 91,
                            Address = "29246 Roxbury Park",
                            FdSignal = "37",
                            Incident = 124172,
                            Notes = "Focused zero tolerance complexity",
                            PdSignal = "49",
                            Position = 147,
                            Time = new DateTime(2020, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 92,
                            Address = "5805 Dexter Place",
                            FdSignal = "15",
                            Incident = 929592,
                            Notes = "Front-line discrete policy",
                            PdSignal = "20",
                            Position = 112,
                            Time = new DateTime(2012, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 93,
                            Address = "768 Maywood Avenue",
                            FdSignal = "18",
                            Incident = 986208,
                            Notes = "Assimilated high-level ability",
                            PdSignal = "43",
                            Position = 144,
                            Time = new DateTime(2013, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 94,
                            Address = "85 Homewood Lane",
                            FdSignal = "40",
                            Incident = 966315,
                            Notes = "Horizontal asynchronous superstructure",
                            PdSignal = "51",
                            Position = 110,
                            Time = new DateTime(2012, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 95,
                            Address = "47962 Fuller Terrace",
                            FdSignal = "15",
                            Incident = 374980,
                            Notes = "Progressive exuding flexibility",
                            PdSignal = "13",
                            Position = 107,
                            Time = new DateTime(1999, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 96,
                            Address = "41223 Calypso Circle",
                            FdSignal = "42",
                            Incident = 399710,
                            Notes = "Enterprise-wide dynamic analyzer",
                            PdSignal = "49",
                            Position = 149,
                            Time = new DateTime(2008, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 97,
                            Address = "7 Eagan Trail",
                            FdSignal = "15",
                            Incident = 395087,
                            Notes = "Quality-focused discrete strategy",
                            PdSignal = "16",
                            Position = 122,
                            Time = new DateTime(2020, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 98,
                            Address = "6653 Sage Avenue",
                            FdSignal = "34",
                            Incident = 431106,
                            Notes = "Future-proofed logistical protocol",
                            PdSignal = "53",
                            Position = 159,
                            Time = new DateTime(2011, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 99,
                            Address = "2159 Cordelia Park",
                            FdSignal = "25",
                            Incident = 183348,
                            Notes = "Configurable asynchronous archive",
                            PdSignal = "16",
                            Position = 126,
                            Time = new DateTime(2000, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 100,
                            Address = "05582 Larry Hill",
                            FdSignal = "49",
                            Incident = 625218,
                            Notes = "Re-engineered heuristic approach",
                            PdSignal = "53",
                            Position = 123,
                            Time = new DateTime(2001, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
