// <auto-generated />
using KSheet3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KSheet3.Migrations
{
    [DbContext(typeof(CallContext))]
    [Migration("20240205040603_SeedData2")]
    partial class SeedData2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("KSheet3.Data.Call", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("FdSignal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PdSignal")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Calls", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "7956 Summerview Alley",
                            FdSignal = "30",
                            Notes = "Multi-layered full-range hub",
                            PdSignal = "28",
                            Position = 146
                        },
                        new
                        {
                            Id = 2,
                            Address = "11445 Briar Crest Road",
                            FdSignal = "26",
                            Notes = "Visionary system-worthy groupware",
                            PdSignal = "55",
                            Position = 148
                        },
                        new
                        {
                            Id = 3,
                            Address = "674 Pine View Parkway",
                            FdSignal = "23",
                            Notes = "Visionary coherent archive",
                            PdSignal = "53",
                            Position = 109
                        },
                        new
                        {
                            Id = 4,
                            Address = "1207 Petterle Street",
                            FdSignal = "8",
                            Notes = "Open-source empowering structure",
                            PdSignal = "34",
                            Position = 111
                        },
                        new
                        {
                            Id = 5,
                            Address = "495 Bunker Hill Hill",
                            FdSignal = "13",
                            Notes = "Expanded asymmetric neural-net",
                            PdSignal = "43",
                            Position = 122
                        },
                        new
                        {
                            Id = 6,
                            Address = "92831 Linden Drive",
                            FdSignal = "8",
                            Notes = "User-centric local architecture",
                            PdSignal = "42",
                            Position = 134
                        },
                        new
                        {
                            Id = 7,
                            Address = "97813 Northport Crossing",
                            FdSignal = "2",
                            Notes = "Devolved reciprocal local area network",
                            PdSignal = "3",
                            Position = 120
                        },
                        new
                        {
                            Id = 8,
                            Address = "4293 Novick Avenue",
                            FdSignal = "10",
                            Notes = "Fully-configurable bandwidth-monitored artificial intelligence",
                            PdSignal = "12",
                            Position = 144
                        },
                        new
                        {
                            Id = 9,
                            Address = "93026 Donald Road",
                            FdSignal = "31",
                            Notes = "Open-source dedicated website",
                            PdSignal = "13",
                            Position = 158
                        },
                        new
                        {
                            Id = 10,
                            Address = "70059 Redwing Lane",
                            FdSignal = "5",
                            Notes = "Focused well-modulated open system",
                            PdSignal = "34",
                            Position = 120
                        },
                        new
                        {
                            Id = 11,
                            Address = "7 Spenser Crossing",
                            FdSignal = "22",
                            Notes = "Universal actuating focus group",
                            PdSignal = "48",
                            Position = 104
                        },
                        new
                        {
                            Id = 92,
                            Address = "3 Buhler Avenue",
                            FdSignal = "5",
                            Notes = "Self-enabling 24 hour Graphical User Interface",
                            PdSignal = "8",
                            Position = 146
                        },
                        new
                        {
                            Id = 93,
                            Address = "60465 Fordem Alley",
                            FdSignal = "21",
                            Notes = "Advanced incremental installation",
                            PdSignal = "21",
                            Position = 102
                        },
                        new
                        {
                            Id = 94,
                            Address = "94565 Briar Crest Plaza",
                            FdSignal = "20",
                            Notes = "Reduced neutral installation",
                            PdSignal = "16",
                            Position = 149
                        },
                        new
                        {
                            Id = 95,
                            Address = "74726 Forest Run Terrace",
                            FdSignal = "32",
                            Notes = "User-friendly high-level open architecture",
                            PdSignal = "6",
                            Position = 143
                        },
                        new
                        {
                            Id = 96,
                            Address = "5 Dennis Park",
                            FdSignal = "20",
                            Notes = "Persevering modular initiative",
                            PdSignal = "41",
                            Position = 115
                        },
                        new
                        {
                            Id = 97,
                            Address = "04 Union Junction",
                            FdSignal = "10",
                            Notes = "Horizontal directional matrix",
                            PdSignal = "27",
                            Position = 107
                        },
                        new
                        {
                            Id = 98,
                            Address = "39205 Moulton Place",
                            FdSignal = "8",
                            Notes = "Realigned non-volatile concept",
                            PdSignal = "42",
                            Position = 120
                        },
                        new
                        {
                            Id = 99,
                            Address = "26 Nancy Center",
                            FdSignal = "2",
                            Notes = "Mandatory content-based data-warehouse",
                            PdSignal = "36",
                            Position = 144
                        },
                        new
                        {
                            Id = 100,
                            Address = "09348 Burrows Lane",
                            FdSignal = "1",
                            Notes = "De-engineered multi-state product",
                            PdSignal = "39",
                            Position = 116
                        },
                        new
                        {
                            Id = 101,
                            Address = "24499 Miller Park",
                            FdSignal = "15",
                            Notes = "Triple-buffered homogeneous artificial intelligence",
                            PdSignal = "5",
                            Position = 153
                        },
                        new
                        {
                            Id = 102,
                            Address = "1 Warrior Street",
                            FdSignal = "13",
                            Notes = "Streamlined human-resource service-desk",
                            PdSignal = "24",
                            Position = 132
                        },
                        new
                        {
                            Id = 103,
                            Address = "63 Prairie Rose Plaza",
                            FdSignal = "19",
                            Notes = "User-friendly tertiary customer loyalty",
                            PdSignal = "2",
                            Position = 112
                        },
                        new
                        {
                            Id = 104,
                            Address = "88 Gale Point",
                            FdSignal = "23",
                            Notes = "Future-proofed motivating capacity",
                            PdSignal = "47",
                            Position = 137
                        },
                        new
                        {
                            Id = 105,
                            Address = "11343 Weeping Birch Drive",
                            FdSignal = "8",
                            Notes = "Future-proofed bottom-line toolset",
                            PdSignal = "22",
                            Position = 113
                        },
                        new
                        {
                            Id = 106,
                            Address = "368 Fairview Trail",
                            FdSignal = "1",
                            Notes = "Synergistic bifurcated budgetary management",
                            PdSignal = "49",
                            Position = 109
                        },
                        new
                        {
                            Id = 107,
                            Address = "61 Oxford Plaza",
                            FdSignal = "30",
                            Notes = "Polarised tangible info-mediaries",
                            PdSignal = "26",
                            Position = 128
                        },
                        new
                        {
                            Id = 108,
                            Address = "67 Westend Park",
                            FdSignal = "2",
                            Notes = "Multi-tiered 3rd generation application",
                            PdSignal = "38",
                            Position = 130
                        },
                        new
                        {
                            Id = 109,
                            Address = "624 Hooker Pass",
                            FdSignal = "1",
                            Notes = "Exclusive multi-tasking standardization",
                            PdSignal = "53",
                            Position = 131
                        },
                        new
                        {
                            Id = 110,
                            Address = "448 Tomscot Alley",
                            FdSignal = "31",
                            Notes = "Multi-channelled actuating info-mediaries",
                            PdSignal = "52",
                            Position = 157
                        },
                        new
                        {
                            Id = 111,
                            Address = "1656 Kensington Center",
                            FdSignal = "7",
                            Notes = "Persistent directional matrix",
                            PdSignal = "6",
                            Position = 137
                        },
                        new
                        {
                            Id = 112,
                            Address = "59 Rusk Street",
                            FdSignal = "14",
                            Notes = "Fundamental didactic concept",
                            PdSignal = "22",
                            Position = 123
                        },
                        new
                        {
                            Id = 113,
                            Address = "6 Fuller Alley",
                            FdSignal = "18",
                            Notes = "Fundamental encompassing access",
                            PdSignal = "20",
                            Position = 146
                        },
                        new
                        {
                            Id = 114,
                            Address = "76747 Mendota Hill",
                            FdSignal = "8",
                            Notes = "Ergonomic zero defect throughput",
                            PdSignal = "49",
                            Position = 133
                        },
                        new
                        {
                            Id = 115,
                            Address = "0393 Oxford Place",
                            FdSignal = "32",
                            Notes = "Re-engineered demand-driven framework",
                            PdSignal = "19",
                            Position = 158
                        },
                        new
                        {
                            Id = 116,
                            Address = "63 Mallard Street",
                            FdSignal = "8",
                            Notes = "Re-engineered methodical parallelism",
                            PdSignal = "45",
                            Position = 121
                        },
                        new
                        {
                            Id = 117,
                            Address = "54602 Garrison Court",
                            FdSignal = "25",
                            Notes = "Assimilated eco-centric challenge",
                            PdSignal = "12",
                            Position = 148
                        },
                        new
                        {
                            Id = 118,
                            Address = "4 Arkansas Terrace",
                            FdSignal = "2",
                            Notes = "Decentralized leading edge portal",
                            PdSignal = "38",
                            Position = 124
                        },
                        new
                        {
                            Id = 119,
                            Address = "27495 Arrowood Pass",
                            FdSignal = "10",
                            Notes = "Persevering contextually-based definition",
                            PdSignal = "22",
                            Position = 109
                        },
                        new
                        {
                            Id = 120,
                            Address = "09473 Toban Circle",
                            FdSignal = "23",
                            Notes = "Fundamental analyzing secured line",
                            PdSignal = "40",
                            Position = 106
                        },
                        new
                        {
                            Id = 121,
                            Address = "9 Old Shore Avenue",
                            FdSignal = "5",
                            Notes = "Switchable encompassing circuit",
                            PdSignal = "7",
                            Position = 120
                        },
                        new
                        {
                            Id = 122,
                            Address = "806 Oneill Point",
                            FdSignal = "19",
                            Notes = "Expanded uniform data-warehouse",
                            PdSignal = "48",
                            Position = 116
                        },
                        new
                        {
                            Id = 123,
                            Address = "80 Briar Crest Parkway",
                            FdSignal = "9",
                            Notes = "Vision-oriented 24/7 capability",
                            PdSignal = "17",
                            Position = 154
                        },
                        new
                        {
                            Id = 124,
                            Address = "324 Kenwood Road",
                            FdSignal = "10",
                            Notes = "Total transitional contingency",
                            PdSignal = "48",
                            Position = 126
                        },
                        new
                        {
                            Id = 125,
                            Address = "55 Fuller Terrace",
                            FdSignal = "22",
                            Notes = "Cross-group bi-directional system engine",
                            PdSignal = "54",
                            Position = 114
                        },
                        new
                        {
                            Id = 126,
                            Address = "28 Farmco Point",
                            FdSignal = "5",
                            Notes = "Profound system-worthy superstructure",
                            PdSignal = "48",
                            Position = 108
                        },
                        new
                        {
                            Id = 127,
                            Address = "1 Briar Crest Place",
                            FdSignal = "14",
                            Notes = "Synergistic scalable protocol",
                            PdSignal = "53",
                            Position = 120
                        },
                        new
                        {
                            Id = 128,
                            Address = "1978 Hollow Ridge Hill",
                            FdSignal = "21",
                            Notes = "Upgradable human-resource framework",
                            PdSignal = "40",
                            Position = 117
                        },
                        new
                        {
                            Id = 129,
                            Address = "01 Gale Hill",
                            FdSignal = "27",
                            Notes = "Team-oriented radical website",
                            PdSignal = "42",
                            Position = 113
                        },
                        new
                        {
                            Id = 130,
                            Address = "835 Sunfield Pass",
                            FdSignal = "29",
                            Notes = "Open-architected exuding software",
                            PdSignal = "7",
                            Position = 159
                        },
                        new
                        {
                            Id = 131,
                            Address = "622 Lien Center",
                            FdSignal = "5",
                            Notes = "Public-key system-worthy product",
                            PdSignal = "32",
                            Position = 121
                        },
                        new
                        {
                            Id = 132,
                            Address = "9 Stuart Way",
                            FdSignal = "3",
                            Notes = "Ergonomic reciprocal service-desk",
                            PdSignal = "8",
                            Position = 152
                        },
                        new
                        {
                            Id = 133,
                            Address = "280 Sheridan Center",
                            FdSignal = "30",
                            Notes = "Triple-buffered interactive middleware",
                            PdSignal = "47",
                            Position = 154
                        },
                        new
                        {
                            Id = 134,
                            Address = "542 Fair Oaks Place",
                            FdSignal = "14",
                            Notes = "Grass-roots logistical benchmark",
                            PdSignal = "37",
                            Position = 156
                        },
                        new
                        {
                            Id = 135,
                            Address = "9 Jackson Hill",
                            FdSignal = "14",
                            Notes = "Ameliorated demand-driven array",
                            PdSignal = "4",
                            Position = 127
                        },
                        new
                        {
                            Id = 136,
                            Address = "225 Ryan Lane",
                            FdSignal = "5",
                            Notes = "Pre-emptive dedicated conglomeration",
                            PdSignal = "41",
                            Position = 153
                        },
                        new
                        {
                            Id = 137,
                            Address = "5 Killdeer Pass",
                            FdSignal = "17",
                            Notes = "Diverse directional knowledge user",
                            PdSignal = "1",
                            Position = 158
                        },
                        new
                        {
                            Id = 138,
                            Address = "28503 Oxford Pass",
                            FdSignal = "4",
                            Notes = "Pre-emptive secondary product",
                            PdSignal = "38",
                            Position = 122
                        },
                        new
                        {
                            Id = 139,
                            Address = "32470 Hermina Road",
                            FdSignal = "16",
                            Notes = "Ameliorated dynamic flexibility",
                            PdSignal = "11",
                            Position = 117
                        },
                        new
                        {
                            Id = 140,
                            Address = "3 Scott Trail",
                            FdSignal = "13",
                            Notes = "Down-sized reciprocal frame",
                            PdSignal = "24",
                            Position = 110
                        },
                        new
                        {
                            Id = 141,
                            Address = "3 Talmadge Crossing",
                            FdSignal = "1",
                            Notes = "Cross-group empowering Graphic Interface",
                            PdSignal = "17",
                            Position = 105
                        },
                        new
                        {
                            Id = 142,
                            Address = "729 Heath Parkway",
                            FdSignal = "27",
                            Notes = "Seamless coherent software",
                            PdSignal = "40",
                            Position = 102
                        },
                        new
                        {
                            Id = 143,
                            Address = "83621 Golf Trail",
                            FdSignal = "28",
                            Notes = "Automated attitude-oriented emulation",
                            PdSignal = "2",
                            Position = 149
                        },
                        new
                        {
                            Id = 144,
                            Address = "80126 Haas Drive",
                            FdSignal = "18",
                            Notes = "Customizable system-worthy attitude",
                            PdSignal = "1",
                            Position = 126
                        },
                        new
                        {
                            Id = 145,
                            Address = "955 Pepper Wood Trail",
                            FdSignal = "23",
                            Notes = "Synergistic eco-centric local area network",
                            PdSignal = "14",
                            Position = 145
                        },
                        new
                        {
                            Id = 146,
                            Address = "1765 Grayhawk Road",
                            FdSignal = "3",
                            Notes = "Self-enabling holistic forecast",
                            PdSignal = "8",
                            Position = 110
                        },
                        new
                        {
                            Id = 147,
                            Address = "68458 Pierstorff Circle",
                            FdSignal = "23",
                            Notes = "Balanced dynamic leverage",
                            PdSignal = "14",
                            Position = 129
                        },
                        new
                        {
                            Id = 148,
                            Address = "7639 Tennyson Parkway",
                            FdSignal = "16",
                            Notes = "Horizontal zero administration Graphical User Interface",
                            PdSignal = "19",
                            Position = 143
                        },
                        new
                        {
                            Id = 149,
                            Address = "8941 High Crossing Alley",
                            FdSignal = "17",
                            Notes = "Distributed mission-critical superstructure",
                            PdSignal = "5",
                            Position = 131
                        },
                        new
                        {
                            Id = 150,
                            Address = "8492 Buell Hill",
                            FdSignal = "28",
                            Notes = "Re-engineered zero defect task-force",
                            PdSignal = "7",
                            Position = 137
                        },
                        new
                        {
                            Id = 151,
                            Address = "0 Hagan Junction",
                            FdSignal = "10",
                            Notes = "Focused object-oriented challenge",
                            PdSignal = "33",
                            Position = 160
                        },
                        new
                        {
                            Id = 152,
                            Address = "5457 Harbort Trail",
                            FdSignal = "10",
                            Notes = "Programmable neutral conglomeration",
                            PdSignal = "8",
                            Position = 160
                        },
                        new
                        {
                            Id = 153,
                            Address = "89 Blaine Lane",
                            FdSignal = "15",
                            Notes = "Triple-buffered local solution",
                            PdSignal = "4",
                            Position = 114
                        },
                        new
                        {
                            Id = 154,
                            Address = "07 Iowa Road",
                            FdSignal = "28",
                            Notes = "Mandatory even-keeled ability",
                            PdSignal = "14",
                            Position = 137
                        },
                        new
                        {
                            Id = 155,
                            Address = "1 Sloan Avenue",
                            FdSignal = "30",
                            Notes = "Optional stable solution",
                            PdSignal = "37",
                            Position = 119
                        },
                        new
                        {
                            Id = 156,
                            Address = "72487 Hauk Park",
                            FdSignal = "7",
                            Notes = "Fully-configurable actuating solution",
                            PdSignal = "22",
                            Position = 154
                        },
                        new
                        {
                            Id = 157,
                            Address = "67 Crescent Oaks Point",
                            FdSignal = "17",
                            Notes = "Focused discrete definition",
                            PdSignal = "38",
                            Position = 107
                        },
                        new
                        {
                            Id = 158,
                            Address = "52113 Marcy Center",
                            FdSignal = "2",
                            Notes = "Diverse uniform superstructure",
                            PdSignal = "48",
                            Position = 127
                        },
                        new
                        {
                            Id = 159,
                            Address = "6 7th Junction",
                            FdSignal = "24",
                            Notes = "Up-sized demand-driven methodology",
                            PdSignal = "48",
                            Position = 143
                        },
                        new
                        {
                            Id = 160,
                            Address = "5 Buhler Way",
                            FdSignal = "1",
                            Notes = "Fully-configurable contextually-based budgetary management",
                            PdSignal = "28",
                            Position = 116
                        },
                        new
                        {
                            Id = 161,
                            Address = "9 Express Terrace",
                            FdSignal = "12",
                            Notes = "Virtual holistic open architecture",
                            PdSignal = "54",
                            Position = 123
                        },
                        new
                        {
                            Id = 162,
                            Address = "70397 Stephen Road",
                            FdSignal = "24",
                            Notes = "Optional disintermediate installation",
                            PdSignal = "19",
                            Position = 110
                        },
                        new
                        {
                            Id = 163,
                            Address = "9936 Manley Court",
                            FdSignal = "16",
                            Notes = "Extended multi-state Graphical User Interface",
                            PdSignal = "29",
                            Position = 102
                        },
                        new
                        {
                            Id = 164,
                            Address = "9829 Clyde Gallagher Circle",
                            FdSignal = "11",
                            Notes = "Operative non-volatile orchestration",
                            PdSignal = "43",
                            Position = 159
                        },
                        new
                        {
                            Id = 165,
                            Address = "6 Norway Maple Hill",
                            FdSignal = "24",
                            Notes = "De-engineered background help-desk",
                            PdSignal = "33",
                            Position = 114
                        },
                        new
                        {
                            Id = 166,
                            Address = "7 Nelson Park",
                            FdSignal = "3",
                            Notes = "Configurable responsive moratorium",
                            PdSignal = "38",
                            Position = 146
                        },
                        new
                        {
                            Id = 167,
                            Address = "19123 Lunder Alley",
                            FdSignal = "8",
                            Notes = "Organized web-enabled implementation",
                            PdSignal = "20",
                            Position = 105
                        },
                        new
                        {
                            Id = 168,
                            Address = "34555 Daystar Crossing",
                            FdSignal = "25",
                            Notes = "Streamlined next generation secured line",
                            PdSignal = "40",
                            Position = 156
                        },
                        new
                        {
                            Id = 169,
                            Address = "86637 Corscot Point",
                            FdSignal = "27",
                            Notes = "Reactive solution-oriented orchestration",
                            PdSignal = "43",
                            Position = 154
                        },
                        new
                        {
                            Id = 170,
                            Address = "38 American Ash Park",
                            FdSignal = "28",
                            Notes = "Fundamental fault-tolerant service-desk",
                            PdSignal = "52",
                            Position = 150
                        },
                        new
                        {
                            Id = 171,
                            Address = "546 Grasskamp Crossing",
                            FdSignal = "25",
                            Notes = "Reduced modular extranet",
                            PdSignal = "50",
                            Position = 102
                        },
                        new
                        {
                            Id = 172,
                            Address = "75 Express Drive",
                            FdSignal = "2",
                            Notes = "Extended value-added circuit",
                            PdSignal = "36",
                            Position = 130
                        },
                        new
                        {
                            Id = 173,
                            Address = "40 Homewood Alley",
                            FdSignal = "5",
                            Notes = "Integrated scalable superstructure",
                            PdSignal = "7",
                            Position = 145
                        },
                        new
                        {
                            Id = 174,
                            Address = "4707 Gina Pass",
                            FdSignal = "13",
                            Notes = "Function-based well-modulated system engine",
                            PdSignal = "41",
                            Position = 146
                        },
                        new
                        {
                            Id = 175,
                            Address = "805 Sommers Crossing",
                            FdSignal = "25",
                            Notes = "Expanded web-enabled structure",
                            PdSignal = "15",
                            Position = 140
                        },
                        new
                        {
                            Id = 176,
                            Address = "99193 Eggendart Junction",
                            FdSignal = "7",
                            Notes = "Intuitive optimal hub",
                            PdSignal = "45",
                            Position = 132
                        },
                        new
                        {
                            Id = 177,
                            Address = "34 Summerview Park",
                            FdSignal = "10",
                            Notes = "Persevering impactful policy",
                            PdSignal = "33",
                            Position = 103
                        },
                        new
                        {
                            Id = 178,
                            Address = "7848 Cambridge Parkway",
                            FdSignal = "23",
                            Notes = "Business-focused scalable access",
                            PdSignal = "47",
                            Position = 133
                        },
                        new
                        {
                            Id = 179,
                            Address = "3 Cambridge Road",
                            FdSignal = "20",
                            Notes = "Public-key even-keeled time-frame",
                            PdSignal = "31",
                            Position = 132
                        },
                        new
                        {
                            Id = 180,
                            Address = "92 Lunder Crossing",
                            FdSignal = "22",
                            Notes = "Re-contextualized 3rd generation data-warehouse",
                            PdSignal = "21",
                            Position = 142
                        },
                        new
                        {
                            Id = 181,
                            Address = "296 Dorton Hill",
                            FdSignal = "4",
                            Notes = "Triple-buffered demand-driven core",
                            PdSignal = "54",
                            Position = 120
                        },
                        new
                        {
                            Id = 182,
                            Address = "941 Fallview Junction",
                            FdSignal = "22",
                            Notes = "Streamlined stable frame",
                            PdSignal = "2",
                            Position = 137
                        },
                        new
                        {
                            Id = 183,
                            Address = "48 Gulseth Drive",
                            FdSignal = "15",
                            Notes = "Stand-alone non-volatile installation",
                            PdSignal = "11",
                            Position = 122
                        },
                        new
                        {
                            Id = 184,
                            Address = "224 Express Way",
                            FdSignal = "23",
                            Notes = "Public-key zero tolerance product",
                            PdSignal = "39",
                            Position = 119
                        },
                        new
                        {
                            Id = 185,
                            Address = "38 Ronald Regan Pass",
                            FdSignal = "14",
                            Notes = "Universal asymmetric application",
                            PdSignal = "35",
                            Position = 124
                        },
                        new
                        {
                            Id = 186,
                            Address = "68010 Heath Plaza",
                            FdSignal = "18",
                            Notes = "Persevering 24 hour installation",
                            PdSignal = "32",
                            Position = 144
                        },
                        new
                        {
                            Id = 187,
                            Address = "50869 Arapahoe Court",
                            FdSignal = "4",
                            Notes = "Synergistic 24 hour success",
                            PdSignal = "55",
                            Position = 106
                        },
                        new
                        {
                            Id = 188,
                            Address = "6986 Buena Vista Drive",
                            FdSignal = "16",
                            Notes = "Inverse leading edge matrices",
                            PdSignal = "4",
                            Position = 114
                        },
                        new
                        {
                            Id = 189,
                            Address = "3162 Crowley Alley",
                            FdSignal = "28",
                            Notes = "Persevering logistical synergy",
                            PdSignal = "15",
                            Position = 135
                        },
                        new
                        {
                            Id = 190,
                            Address = "7958 Lyons Way",
                            FdSignal = "3",
                            Notes = "Up-sized bottom-line framework",
                            PdSignal = "6",
                            Position = 147
                        },
                        new
                        {
                            Id = 191,
                            Address = "977 Bayside Park",
                            FdSignal = "9",
                            Notes = "De-engineered national pricing structure",
                            PdSignal = "48",
                            Position = 102
                        },
                        new
                        {
                            Id = 192,
                            Address = "6079 Summer Ridge Crossing",
                            FdSignal = "12",
                            Notes = "Persevering global time-frame",
                            PdSignal = "31",
                            Position = 102
                        },
                        new
                        {
                            Id = 193,
                            Address = "3 Anniversary Street",
                            FdSignal = "6",
                            Notes = "Fully-configurable multi-tasking time-frame",
                            PdSignal = "16",
                            Position = 119
                        },
                        new
                        {
                            Id = 194,
                            Address = "3 Mayfield Hill",
                            FdSignal = "6",
                            Notes = "Reduced object-oriented extranet",
                            PdSignal = "51",
                            Position = 134
                        },
                        new
                        {
                            Id = 195,
                            Address = "966 Harper Pass",
                            FdSignal = "25",
                            Notes = "Enterprise-wide clear-thinking service-desk",
                            PdSignal = "50",
                            Position = 132
                        },
                        new
                        {
                            Id = 196,
                            Address = "01179 Muir Alley",
                            FdSignal = "21",
                            Notes = "Progressive real-time success",
                            PdSignal = "34",
                            Position = 138
                        },
                        new
                        {
                            Id = 197,
                            Address = "95 Anniversary Place",
                            FdSignal = "30",
                            Notes = "Enterprise-wide logistical algorithm",
                            PdSignal = "26",
                            Position = 144
                        },
                        new
                        {
                            Id = 198,
                            Address = "4 Rockefeller Plaza",
                            FdSignal = "3",
                            Notes = "Ameliorated zero tolerance help-desk",
                            PdSignal = "27",
                            Position = 155
                        },
                        new
                        {
                            Id = 199,
                            Address = "0753 Holy Cross Circle",
                            FdSignal = "8",
                            Notes = "Profit-focused tangible focus group",
                            PdSignal = "51",
                            Position = 157
                        },
                        new
                        {
                            Id = 200,
                            Address = "0452 Oneill Avenue",
                            FdSignal = "14",
                            Notes = "Enhanced tangible archive",
                            PdSignal = "28",
                            Position = 133
                        },
                        new
                        {
                            Id = 201,
                            Address = "39 Ridgeway Road",
                            FdSignal = "4",
                            Notes = "Grass-roots intangible archive",
                            PdSignal = "50",
                            Position = 136
                        },
                        new
                        {
                            Id = 202,
                            Address = "5 Trailsway Avenue",
                            FdSignal = "18",
                            Notes = "Configurable value-added productivity",
                            PdSignal = "24",
                            Position = 144
                        },
                        new
                        {
                            Id = 203,
                            Address = "13 Hollow Ridge Trail",
                            FdSignal = "11",
                            Notes = "User-friendly neutral service-desk",
                            PdSignal = "36",
                            Position = 107
                        },
                        new
                        {
                            Id = 204,
                            Address = "97036 6th Terrace",
                            FdSignal = "32",
                            Notes = "Triple-buffered regional encryption",
                            PdSignal = "17",
                            Position = 133
                        },
                        new
                        {
                            Id = 205,
                            Address = "96852 Warrior Parkway",
                            FdSignal = "32",
                            Notes = "Public-key empowering installation",
                            PdSignal = "11",
                            Position = 139
                        },
                        new
                        {
                            Id = 206,
                            Address = "18986 Duke Place",
                            FdSignal = "18",
                            Notes = "Focused intangible policy",
                            PdSignal = "25",
                            Position = 130
                        },
                        new
                        {
                            Id = 207,
                            Address = "23771 Mallard Center",
                            FdSignal = "30",
                            Notes = "Ergonomic heuristic challenge",
                            PdSignal = "51",
                            Position = 151
                        },
                        new
                        {
                            Id = 208,
                            Address = "71 Straubel Street",
                            FdSignal = "12",
                            Notes = "Function-based static adapter",
                            PdSignal = "22",
                            Position = 151
                        },
                        new
                        {
                            Id = 209,
                            Address = "9 Kensington Place",
                            FdSignal = "25",
                            Notes = "Self-enabling real-time collaboration",
                            PdSignal = "23",
                            Position = 159
                        },
                        new
                        {
                            Id = 210,
                            Address = "4729 Katie Park",
                            FdSignal = "15",
                            Notes = "Synergistic contextually-based flexibility",
                            PdSignal = "1",
                            Position = 150
                        },
                        new
                        {
                            Id = 211,
                            Address = "32 Schurz Park",
                            FdSignal = "11",
                            Notes = "Face to face needs-based focus group",
                            PdSignal = "27",
                            Position = 154
                        },
                        new
                        {
                            Id = 212,
                            Address = "52059 Fair Oaks Road",
                            FdSignal = "6",
                            Notes = "Digitized mobile system engine",
                            PdSignal = "48",
                            Position = 119
                        },
                        new
                        {
                            Id = 213,
                            Address = "9 Butternut Lane",
                            FdSignal = "18",
                            Notes = "User-centric zero administration hub",
                            PdSignal = "27",
                            Position = 128
                        },
                        new
                        {
                            Id = 214,
                            Address = "6 Mesta Trail",
                            FdSignal = "28",
                            Notes = "Operative systematic approach",
                            PdSignal = "53",
                            Position = 113
                        },
                        new
                        {
                            Id = 215,
                            Address = "8 Caliangt Parkway",
                            FdSignal = "20",
                            Notes = "Focused system-worthy framework",
                            PdSignal = "48",
                            Position = 133
                        },
                        new
                        {
                            Id = 216,
                            Address = "8 Laurel Terrace",
                            FdSignal = "6",
                            Notes = "Devolved global portal",
                            PdSignal = "2",
                            Position = 152
                        },
                        new
                        {
                            Id = 217,
                            Address = "6 Warbler Road",
                            FdSignal = "22",
                            Notes = "Synchronised static artificial intelligence",
                            PdSignal = "11",
                            Position = 143
                        },
                        new
                        {
                            Id = 218,
                            Address = "450 Roth Alley",
                            FdSignal = "17",
                            Notes = "Fully-configurable tangible hardware",
                            PdSignal = "33",
                            Position = 102
                        },
                        new
                        {
                            Id = 219,
                            Address = "538 Crowley Alley",
                            FdSignal = "19",
                            Notes = "Realigned client-driven encryption",
                            PdSignal = "43",
                            Position = 113
                        },
                        new
                        {
                            Id = 220,
                            Address = "0 Eastwood Plaza",
                            FdSignal = "29",
                            Notes = "Multi-tiered object-oriented moderator",
                            PdSignal = "43",
                            Position = 125
                        },
                        new
                        {
                            Id = 221,
                            Address = "5 Arkansas Pass",
                            FdSignal = "20",
                            Notes = "Inverse local focus group",
                            PdSignal = "46",
                            Position = 154
                        },
                        new
                        {
                            Id = 222,
                            Address = "19 Sachtjen Hill",
                            FdSignal = "12",
                            Notes = "Distributed didactic complexity",
                            PdSignal = "14",
                            Position = 103
                        },
                        new
                        {
                            Id = 223,
                            Address = "424 Moose Terrace",
                            FdSignal = "10",
                            Notes = "Organized web-enabled toolset",
                            PdSignal = "4",
                            Position = 111
                        },
                        new
                        {
                            Id = 224,
                            Address = "38 Montana Way",
                            FdSignal = "9",
                            Notes = "Synchronised 5th generation moderator",
                            PdSignal = "49",
                            Position = 130
                        },
                        new
                        {
                            Id = 225,
                            Address = "70 Meadow Ridge Center",
                            FdSignal = "6",
                            Notes = "Cross-group mission-critical website",
                            PdSignal = "7",
                            Position = 124
                        },
                        new
                        {
                            Id = 226,
                            Address = "006 Dexter Hill",
                            FdSignal = "4",
                            Notes = "Visionary human-resource function",
                            PdSignal = "28",
                            Position = 126
                        },
                        new
                        {
                            Id = 227,
                            Address = "7800 Laurel Alley",
                            FdSignal = "20",
                            Notes = "Up-sized directional architecture",
                            PdSignal = "43",
                            Position = 158
                        },
                        new
                        {
                            Id = 228,
                            Address = "16209 Northwestern Circle",
                            FdSignal = "26",
                            Notes = "Upgradable systematic workforce",
                            PdSignal = "9",
                            Position = 121
                        },
                        new
                        {
                            Id = 229,
                            Address = "3557 Calypso Place",
                            FdSignal = "22",
                            Notes = "Customizable bottom-line projection",
                            PdSignal = "13",
                            Position = 147
                        },
                        new
                        {
                            Id = 230,
                            Address = "67 Rusk Terrace",
                            FdSignal = "13",
                            Notes = "Profound didactic task-force",
                            PdSignal = "45",
                            Position = 147
                        },
                        new
                        {
                            Id = 231,
                            Address = "6 Killdeer Place",
                            FdSignal = "29",
                            Notes = "Organic human-resource contingency",
                            PdSignal = "18",
                            Position = 145
                        },
                        new
                        {
                            Id = 232,
                            Address = "2 Union Center",
                            FdSignal = "4",
                            Notes = "Advanced scalable attitude",
                            PdSignal = "5",
                            Position = 131
                        },
                        new
                        {
                            Id = 233,
                            Address = "8094 Sunfield Parkway",
                            FdSignal = "13",
                            Notes = "Sharable scalable budgetary management",
                            PdSignal = "43",
                            Position = 159
                        },
                        new
                        {
                            Id = 234,
                            Address = "7631 Marcy Lane",
                            FdSignal = "6",
                            Notes = "Synergized 4th generation projection",
                            PdSignal = "28",
                            Position = 157
                        },
                        new
                        {
                            Id = 235,
                            Address = "5088 Golden Leaf Way",
                            FdSignal = "4",
                            Notes = "Reduced system-worthy challenge",
                            PdSignal = "31",
                            Position = 109
                        },
                        new
                        {
                            Id = 236,
                            Address = "23277 Becker Place",
                            FdSignal = "2",
                            Notes = "Profit-focused executive benchmark",
                            PdSignal = "27",
                            Position = 105
                        },
                        new
                        {
                            Id = 237,
                            Address = "75663 Southridge Hill",
                            FdSignal = "12",
                            Notes = "Realigned executive orchestration",
                            PdSignal = "10",
                            Position = 126
                        },
                        new
                        {
                            Id = 238,
                            Address = "81184 Huxley Circle",
                            FdSignal = "23",
                            Notes = "Multi-layered zero defect collaboration",
                            PdSignal = "25",
                            Position = 144
                        },
                        new
                        {
                            Id = 239,
                            Address = "67 Morningstar Terrace",
                            FdSignal = "15",
                            Notes = "Multi-lateral human-resource Graphic Interface",
                            PdSignal = "4",
                            Position = 102
                        },
                        new
                        {
                            Id = 240,
                            Address = "220 Northland Drive",
                            FdSignal = "12",
                            Notes = "Inverse national help-desk",
                            PdSignal = "45",
                            Position = 133
                        },
                        new
                        {
                            Id = 241,
                            Address = "823 Farwell Junction",
                            FdSignal = "3",
                            Notes = "Streamlined object-oriented access",
                            PdSignal = "12",
                            Position = 141
                        },
                        new
                        {
                            Id = 242,
                            Address = "29 Moulton Point",
                            FdSignal = "7",
                            Notes = "Pre-emptive modular service-desk",
                            PdSignal = "22",
                            Position = 102
                        },
                        new
                        {
                            Id = 243,
                            Address = "4337 Northridge Avenue",
                            FdSignal = "10",
                            Notes = "Versatile 24/7 encoding",
                            PdSignal = "42",
                            Position = 144
                        },
                        new
                        {
                            Id = 244,
                            Address = "63218 Twin Pines Plaza",
                            FdSignal = "6",
                            Notes = "Business-focused transitional attitude",
                            PdSignal = "28",
                            Position = 137
                        },
                        new
                        {
                            Id = 245,
                            Address = "57667 Main Way",
                            FdSignal = "14",
                            Notes = "Programmable value-added toolset",
                            PdSignal = "19",
                            Position = 146
                        },
                        new
                        {
                            Id = 246,
                            Address = "09203 Leroy Court",
                            FdSignal = "25",
                            Notes = "Business-focused encompassing matrices",
                            PdSignal = "36",
                            Position = 156
                        },
                        new
                        {
                            Id = 247,
                            Address = "6 Parkside Road",
                            FdSignal = "11",
                            Notes = "Multi-layered logistical time-frame",
                            PdSignal = "7",
                            Position = 126
                        },
                        new
                        {
                            Id = 248,
                            Address = "530 Blackbird Pass",
                            FdSignal = "24",
                            Notes = "Fundamental national capacity",
                            PdSignal = "50",
                            Position = 157
                        },
                        new
                        {
                            Id = 249,
                            Address = "291 Basil Crossing",
                            FdSignal = "2",
                            Notes = "Programmable eco-centric alliance",
                            PdSignal = "20",
                            Position = 160
                        },
                        new
                        {
                            Id = 250,
                            Address = "57 West Circle",
                            FdSignal = "24",
                            Notes = "Future-proofed mobile emulation",
                            PdSignal = "43",
                            Position = 136
                        },
                        new
                        {
                            Id = 251,
                            Address = "8390 Delaware Junction",
                            FdSignal = "20",
                            Notes = "Assimilated eco-centric synergy",
                            PdSignal = "37",
                            Position = 125
                        },
                        new
                        {
                            Id = 252,
                            Address = "397 Corscot Lane",
                            FdSignal = "27",
                            Notes = "Mandatory content-based infrastructure",
                            PdSignal = "15",
                            Position = 101
                        },
                        new
                        {
                            Id = 253,
                            Address = "22 Welch Plaza",
                            FdSignal = "4",
                            Notes = "Future-proofed context-sensitive knowledge user",
                            PdSignal = "27",
                            Position = 131
                        },
                        new
                        {
                            Id = 254,
                            Address = "598 Packers Crossing",
                            FdSignal = "11",
                            Notes = "Focused reciprocal intranet",
                            PdSignal = "15",
                            Position = 144
                        },
                        new
                        {
                            Id = 255,
                            Address = "0 Barby Road",
                            FdSignal = "17",
                            Notes = "Persistent human-resource initiative",
                            PdSignal = "51",
                            Position = 113
                        },
                        new
                        {
                            Id = 256,
                            Address = "41920 Meadow Valley Park",
                            FdSignal = "26",
                            Notes = "Optimized systematic alliance",
                            PdSignal = "22",
                            Position = 101
                        },
                        new
                        {
                            Id = 257,
                            Address = "7 Barnett Junction",
                            FdSignal = "7",
                            Notes = "User-friendly systematic archive",
                            PdSignal = "42",
                            Position = 130
                        },
                        new
                        {
                            Id = 258,
                            Address = "5 Charing Cross Road",
                            FdSignal = "7",
                            Notes = "Versatile composite conglomeration",
                            PdSignal = "23",
                            Position = 102
                        },
                        new
                        {
                            Id = 259,
                            Address = "10394 Emmet Lane",
                            FdSignal = "30",
                            Notes = "Face to face dedicated Graphic Interface",
                            PdSignal = "47",
                            Position = 107
                        },
                        new
                        {
                            Id = 260,
                            Address = "2 Boyd Pass",
                            FdSignal = "14",
                            Notes = "Enterprise-wide demand-driven migration",
                            PdSignal = "16",
                            Position = 115
                        },
                        new
                        {
                            Id = 261,
                            Address = "341 Jana Point",
                            FdSignal = "18",
                            Notes = "Triple-buffered value-added framework",
                            PdSignal = "11",
                            Position = 139
                        },
                        new
                        {
                            Id = 262,
                            Address = "0 Hanson Parkway",
                            FdSignal = "25",
                            Notes = "Reduced reciprocal encoding",
                            PdSignal = "11",
                            Position = 122
                        },
                        new
                        {
                            Id = 263,
                            Address = "1 North Terrace",
                            FdSignal = "11",
                            Notes = "Reverse-engineered multimedia benchmark",
                            PdSignal = "9",
                            Position = 130
                        },
                        new
                        {
                            Id = 264,
                            Address = "5 Rusk Park",
                            FdSignal = "20",
                            Notes = "Right-sized client-driven hardware",
                            PdSignal = "17",
                            Position = 124
                        },
                        new
                        {
                            Id = 265,
                            Address = "6589 Prairieview Parkway",
                            FdSignal = "5",
                            Notes = "Triple-buffered secondary productivity",
                            PdSignal = "53",
                            Position = 145
                        },
                        new
                        {
                            Id = 266,
                            Address = "710 Ridgeview Parkway",
                            FdSignal = "29",
                            Notes = "Self-enabling leading edge methodology",
                            PdSignal = "17",
                            Position = 139
                        },
                        new
                        {
                            Id = 267,
                            Address = "21 Sugar Lane",
                            FdSignal = "23",
                            Notes = "Persevering optimizing productivity",
                            PdSignal = "34",
                            Position = 103
                        },
                        new
                        {
                            Id = 268,
                            Address = "45546 Holy Cross Hill",
                            FdSignal = "25",
                            Notes = "Business-focused system-worthy contingency",
                            PdSignal = "44",
                            Position = 128
                        },
                        new
                        {
                            Id = 269,
                            Address = "2070 Northport Terrace",
                            FdSignal = "29",
                            Notes = "Realigned bifurcated core",
                            PdSignal = "52",
                            Position = 149
                        },
                        new
                        {
                            Id = 270,
                            Address = "89 Anhalt Circle",
                            FdSignal = "15",
                            Notes = "Synergized bottom-line access",
                            PdSignal = "33",
                            Position = 148
                        },
                        new
                        {
                            Id = 271,
                            Address = "8 Carberry Plaza",
                            FdSignal = "13",
                            Notes = "Realigned asymmetric software",
                            PdSignal = "7",
                            Position = 104
                        },
                        new
                        {
                            Id = 272,
                            Address = "9015 South Point",
                            FdSignal = "18",
                            Notes = "Enterprise-wide client-driven circuit",
                            PdSignal = "31",
                            Position = 148
                        },
                        new
                        {
                            Id = 273,
                            Address = "4403 Gateway Way",
                            FdSignal = "6",
                            Notes = "Self-enabling full-range access",
                            PdSignal = "28",
                            Position = 112
                        },
                        new
                        {
                            Id = 274,
                            Address = "8184 Kenwood Court",
                            FdSignal = "25",
                            Notes = "Ameliorated exuding knowledge user",
                            PdSignal = "13",
                            Position = 116
                        },
                        new
                        {
                            Id = 275,
                            Address = "56010 Pawling Road",
                            FdSignal = "4",
                            Notes = "Grass-roots bottom-line algorithm",
                            PdSignal = "44",
                            Position = 152
                        },
                        new
                        {
                            Id = 276,
                            Address = "6204 Chinook Trail",
                            FdSignal = "26",
                            Notes = "Right-sized composite encoding",
                            PdSignal = "47",
                            Position = 113
                        },
                        new
                        {
                            Id = 277,
                            Address = "00 Oakridge Street",
                            FdSignal = "14",
                            Notes = "Inverse background strategy",
                            PdSignal = "42",
                            Position = 139
                        },
                        new
                        {
                            Id = 278,
                            Address = "1276 Kenwood Pass",
                            FdSignal = "4",
                            Notes = "Integrated multimedia structure",
                            PdSignal = "28",
                            Position = 156
                        },
                        new
                        {
                            Id = 279,
                            Address = "50 Debra Road",
                            FdSignal = "18",
                            Notes = "Cross-group secondary orchestration",
                            PdSignal = "26",
                            Position = 122
                        },
                        new
                        {
                            Id = 280,
                            Address = "731 Red Cloud Junction",
                            FdSignal = "31",
                            Notes = "Triple-buffered stable secured line",
                            PdSignal = "48",
                            Position = 124
                        },
                        new
                        {
                            Id = 281,
                            Address = "5855 Little Fleur Street",
                            FdSignal = "28",
                            Notes = "Robust heuristic support",
                            PdSignal = "36",
                            Position = 157
                        },
                        new
                        {
                            Id = 440,
                            Address = "1937 Sage Crossing",
                            FdSignal = "14",
                            Notes = "De-engineered national customer loyalty",
                            PdSignal = "2",
                            Position = 109
                        },
                        new
                        {
                            Id = 441,
                            Address = "26 Riverside Road",
                            FdSignal = "15",
                            Notes = "De-engineered 5th generation archive",
                            PdSignal = "54",
                            Position = 143
                        },
                        new
                        {
                            Id = 990,
                            Address = "1 Kings Terrace",
                            FdSignal = "10",
                            Notes = "Re-contextualized secondary data-warehouse",
                            PdSignal = "47",
                            Position = 140
                        },
                        new
                        {
                            Id = 991,
                            Address = "06674 Cascade Park",
                            FdSignal = "1",
                            Notes = "Quality-focused cohesive Graphical User Interface",
                            PdSignal = "47",
                            Position = 104
                        },
                        new
                        {
                            Id = 992,
                            Address = "3755 Blaine Trail",
                            FdSignal = "31",
                            Notes = "Advanced human-resource collaboration",
                            PdSignal = "26",
                            Position = 157
                        },
                        new
                        {
                            Id = 993,
                            Address = "24793 Menomonie Park",
                            FdSignal = "31",
                            Notes = "Customer-focused responsive implementation",
                            PdSignal = "42",
                            Position = 155
                        },
                        new
                        {
                            Id = 994,
                            Address = "7 Spohn Trail",
                            FdSignal = "12",
                            Notes = "Fundamental neutral model",
                            PdSignal = "16",
                            Position = 151
                        },
                        new
                        {
                            Id = 995,
                            Address = "47133 Mendota Hill",
                            FdSignal = "2",
                            Notes = "Organized object-oriented interface",
                            PdSignal = "22",
                            Position = 141
                        },
                        new
                        {
                            Id = 996,
                            Address = "06 Basil Lane",
                            FdSignal = "24",
                            Notes = "Expanded context-sensitive infrastructure",
                            PdSignal = "21",
                            Position = 146
                        },
                        new
                        {
                            Id = 997,
                            Address = "8 Vidon Street",
                            FdSignal = "14",
                            Notes = "User-centric impactful matrix",
                            PdSignal = "18",
                            Position = 150
                        },
                        new
                        {
                            Id = 998,
                            Address = "5797 Eastlawn Circle",
                            FdSignal = "28",
                            Notes = "Switchable client-driven paradigm",
                            PdSignal = "33",
                            Position = 141
                        },
                        new
                        {
                            Id = 999,
                            Address = "8056 Westend Plaza",
                            FdSignal = "13",
                            Notes = "Optional encompassing artificial intelligence",
                            PdSignal = "48",
                            Position = 131
                        },
                        new
                        {
                            Id = 1000,
                            Address = "29 Hansons Way",
                            FdSignal = "25",
                            Notes = "Centralized regional ability",
                            PdSignal = "27",
                            Position = 137
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
